name: trip_helper
description: A Flutter app to help travelers plan road trips with expense estimation
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.2
  
  # Maps & Location
  google_maps_flutter: ^2.5.0
  location: ^5.0.3
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  
  # HTTP & Data
  http: ^1.1.0
  shared_preferences: ^2.2.2
  
  # State Management
  provider: ^6.1.1
  
  # Ads
  google_mobile_ads: ^4.0.0
  
  # Utils
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true